kind: pinpeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hellox
  - echo world
  
- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo
  
node:
  type: build
