kind: pipeline
type: ssh
name: default

server:
  host: 35.153.105.223
  user: ubuntu
  password: Abc123admin

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - go build
  - go test
